name: Projeto Final GCEIC 2024
on: [push]
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Gera siada do Github context
        run: echo "${{ toJSON(github) }}"
      - name : Mostra mensagem
        run: echo "Alo turma"
      - name :  Lista diretorio
        run: ls -la 
  
  getCode:
    runs-on: ubuntu-latest
    steps:
      - name:  Get code from repositori to evaluate
        uses: actions/checkout@v3
      - name: lista diretorio
        run: ls -la 
      - name: desce um diretorio
        run: cd ..  
      - name: lista 
        run: ls -la 

      - name: lista work directory
        run: ls -la /home/runner/work/projeto_GCEIC24


  test:
    needs: getCode
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Get Code from repository
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3	
        with:
          node-version: ${{ matrix.node-version }}
      - name: Instala Dependencias
        run: npm ci
      - name: Run Lint
        run: npm run lint 
          # aqui uma entrada para cada teste
      - name: Roda os testes
        run: npm test
      - name: Gera o Relatório dos testes
        uses: dorny/test-reporter@v1
        if: success() || failure()  # roda de qualquer maneira
        with:
          name: JEST tests
          path: j*.xml
          reporter: jest-junit


  Deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Faz sincronismo com o Glitch
        uses: kanadgupta/glitch-sync@v3.0.1
        with:
            auth-token: '${{ secrets.authToken }}'
            project-id: '${{ secrets.projectId }}'

  Funcional:
    needs: Deploy
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3	
        with:
          node-version: ${{ matrix.node-version }}
      - name: Instala Dependencias
        run: npm ci        
      
      - name: Run teste Funcional no glitch
        run: npm run F-test

      - name: fotos da tela
        uses: actions/upload-artifact@v4
        with:
          name: Fotos dos testes
          # Path to the release files          
          # Gravar as fotos na raiz do projeto no docker
          path: /home/runner/work/projeto_GCEIC24/fotos/*.png  