name: Projeto Final GCEIC 2024
on: [push]
jobs:
  # info:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Gera siada do Github context
  #       run: echo "${{ toJSON(github) }}"
  #     - name : Mostra mensagem
  #       run: echo "Alo turma"
  #     - name :  Lista diretorio
  #       run: ls -la

  getCode:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repositori to evaluate
        uses: actions/checkout@v3
      - name: lista diretorio
        run: ls -la
      - name: desce um diretorio
        run: cd ..
      - name: lista
        run: ls -la

      - name: lista work directory
        run: ls -la /home/runner/work/projeto_GCEIC24/projeto_GCEIC24
      - name: lista work directory
        run: ls -la /home/runner/work/projeto_GCEIC24/projeto_GCEIC24/fotos
      - name: valor do token
        run: echo "${{ secrets.authToken }}"
      - name: valor do token2
        run: echo ${{ secrets.authToken }}
      - name: Print a secret
        run: echo "The secret is ${MY_SECRET}"
        env:
          MY_SECRET: ${{ secrets.authToken }}
      - name: Pass Secret to Bash Script
        run: |
          chmod +x script.sh
          ./script.sh
        env:
          MY_SECRET: ${{ secrets.authToken }}

  test:
    needs: getCode
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Get Code from repository
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Instala Dependencias
        run: npm ci
      - name: Run Lint
        run:
          npm run lint
          # aqui uma entrada para cada teste
      - name: Roda os testes
        run: npm test
      - name: Gera o Relatório dos testes
        uses: dorny/test-reporter@v1
        if: success() || failure() # roda de qualquer maneira
        with:
          name: JEST tests
          path: j*.xml
          reporter: jest-junit

  Deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Faz sincronismo com o Glitch
        uses: kanadgupta/glitch-sync@v3.0.1
        with:
          auth-token: "${{ secrets.authToken }}"
          project-id: "${{ secrets.projectId }}"

  Funcional:
    needs: Deploy
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Instala Dependencias
        run: npm ci

      - name: Run teste Exemplo Funcional no glitch
        run: npm run F-test

      - name: Run teste caloricExpenditure Funcional no glitch
        run: npm run caloricExpenditure-test

      - name: Run teste IRRF Funcional no glitch
        run: npm run irrf-test

      - name: Run teste SDI Funcional no glitch
        run: npm run SDI-test

      - name: Run teste TMB Funcional no glitch
        run: npm run tmb-test

      - name: Run teste Imposto Funcional no glitch
        run: npm run e2e-test

      - name: Run Test contForca Funcional no glitch
        run: npm run contForca-test

      - name: Run Test ifsp Funcional no glitch
        run: npm run ifsp-test

      - name: Run Test roi-devops14 Funcional no glitch
        run: npm run roi-devops14-test
        
      # - name: lista work directory
      #   run: ls -la /home/runner/work/projeto_GCEIC24/projeto_GCEIC24
      # - name: lista work directory
      #   run: ls -la /home/runner/work/projeto_GCEIC24/projeto_GCEIC24/fotos
      # - name: lista work directory
      #   run: ls -la /home/runner/work/projeto_GCEIC24/projeto_GCEIC24/fotos/exemplo
      #
      # - name: fotos da tela
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: Fotos dos testes
      #     # Path to the release files
      #     # Gravar as fotos na raiz do projeto no docker
      #     path: /home/runner/work/projeto_GCEIC24/projeto_GCEIC24/fotos/exemplo/*.png

      - name: fotos da tela
        uses: actions/upload-artifact@v4
        with:
          name: Fotos dos testes
          # Path to the release files
          # Gravar as fotos na raiz do projeto no docker
          path: /home/runner/work/projeto_GCEIC24/projeto_GCEIC24/fotos/**/*.png
