name: Projeto Final GCEIC 2024
on: [push]
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Gera siada do Github context
        run: echo "${{ toJSON(github) }}"
      - name : Mostra mensagem
        run: echo "Alo turma"
      - name :  Lista diretorio
        run: ls -la 
  
  getCode:
    runs-on: ubuntu-latest
    steps:
      - name:  Get code from repositori to evaluate
        uses: actions/checkout@v3
      - name: lista diretorio
        run: ls -la 
  
